<?php
echo "Enrolled Students for this course<br><br>";
$a = $_GET['id'];



if(isset($_GET['to_remove']))
{
    $b=$_GET['to_remove'];
require_once('dbconnect.php');
//echo "delete from enrolled_details where course_id='$a' and id_no='$b'";
$result = mysql_query("delete from enrolled_details where course_id='$a' and id_no='$b'") or die(mysql_error());
 
}
if(isset($_GET['de_enroll']))
{
	$s=$_GET['de_enroll'];
	require_once('dbconnect.php');
	$result = mysql_query("delete from enrolled_details where id_no like '$s%'") or die(mysql_error());
}


?>

<form name="search_form" method="POST" action="#">
    <input type="text" name="search" value="" />
    <input type="submit" value="Search"  />
</form>

<?php
require_once('dbconnect.php');

if (isset($_POST['search']) ) {
    $_GET['search'] = $_POST['search'];
} else {
 
}
$ch=0;
if (isset($_GET['search']) )
{
$s = $_GET['search'];
if ($s == '') {
    echo '<br>You did not enter a search choice.<br>';
    $ch=1;
	}
//echo $s;

$a = $_GET['id'];
if($ch==0){
echo "<a align=right href=facindex.php?page=show&id=".$a."&de_enroll=" . $s . ">   De-Enroll All</a>\n";
$result = mysql_query("select * from enrolled_details where id_no like '$s%'") or die(mysql_error());
while ($row = mysql_fetch_array($result)) {
    $id_no = $row['id_no'];
    $result1 = mysql_query("select name from registered where id_no='$id_no'") or die(mysql_error());
    if ($row1 = mysql_fetch_array($result1)) {
        echo "<div class='enroll'>" . $id_no . "   " . $row1['name'] . "<a href=facindex.php?page=show&id=".$a."&to_remove=" . $id_no . "> Remove </a></div><br>\n";
    } 
}
}
}
else{
$a = $_GET['id'];
$result = mysql_query("select * from enrolled_details where course_id='$a'") or die(mysql_error());
while ($row = mysql_fetch_array($result)) {
    $id_no = $row['id_no'];
    $result1 = mysql_query("select name from registered where id_no='$id_no'") or die(mysql_error());
    if ($row1 = mysql_fetch_array($result1)) {
        echo "<div class='enroll'>" . $id_no . "   " . $row1['name'] . "<a href=facindex.php?page=show&id=".$a."&to_remove=" . $id_no . ">   Remove </a></div><br>\n";
    } 
}
}
?>